#cloud-config 
autoinstall:
    version: 1
    identity:
        realname: 'IPOG'
        hostname: ubuntu-ipog
        username: ipog
        password: "$6$KOXLr8o1HKOQTYo.$.FwCPR9FytDFx/RKNyDAbQi5/fPZOGNV0Iggy/.ncrGKCqsdDyW6G0KGx43/u1ettTStsw5v2kTQAWVpxAOSW1"
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - git
        - wget
        - curl
        - build-essential
        - net-tools
        - vim
        - unzip
        - ubuntu-restricted-extras
        - ubuntu-drivers-common
    updates: all
    shutdown:
        reboot: true
