#cloud-config 
autoinstall:
    version: 1
    identity:
        realname: 'IPOG'
        hostname: ubuntu-ipog
        username: ipog
        password: "grub.pbkdf2.sha512.10000.078B61E90C5177739F1EB856EC029CDE7819D76EFD5F1DC3FC57C10B8233882B206AECFB2D8F405F93139D3708E94FBEF62AF112C04B35CC9C65248F74E6106E.7BF5282969CAAB67C4369070DC6FFFEFF7AE66337FC1DF08F6F6ED659A0E84689024A4ADB1AA775598B3C2A29E161CB45D768A7D3E12C7588DD00811B455D02B"
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - git
        - wget
        - curl
        - build-essential
        - net-tools
        - vim
        - unzip
    updates: all
    shutdown: reboot
